[package]
name = "binary-vec"
description = "A sorted vector that uses binary search"
authors = ["Jeff Anderson"]
license = "MIT"
readme = "README.md"
version = "0.1.3"
edition = "2024"

[dependencies]
